name: SoapUI-Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_soapui:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download SoapUI 5.8.0 Portable ZIP
        run: |
          Invoke-WebRequest -Uri "https://dl.eviware.com/soapuios/5.8.0/SoapUI-5.8.0-windows-bin.zip" `
                            -OutFile "SoapUI.zip" `
                            -Headers @{ "User-Agent" = "Mozilla/5.0" }
        shell: powershell

      - name: Extract SoapUI ZIP
        run: |
          Expand-Archive -Path SoapUI.zip -DestinationPath SoapUI
        shell: powershell

      - name: Run SoapUI Tests
        run: |
          & ".\SoapUI\bin\testrunner.bat" -s "TestSuite4" -c "ValidarCorreoID" ".\testrunner\Project2.xml"
        shell: powershell