name: SoapUI-Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_soapui:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache SoapUI ZIP
        id: cache-soapui
        uses: actions/cache@v3
        with:
          path: SoapUI.zip
          key: soapui-zip-5.8.0

      - name: Download SoapUI ZIP if not cached
        if: steps.cache-soapui.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://dl.eviware.com/soapuios/5.8.0/SoapUI-5.8.0-windows-bin.zip" `
                            -OutFile "SoapUI.zip" `
                            -Headers @{ "User-Agent" = "Mozilla/5.0" } `
                            -UseBasicParsing > $null 2>&1
        shell: powershell

      - name: Extract SoapUI ZIP
        run: |
          Expand-Archive -Path SoapUI.zip -DestinationPath SoapUI -Force
        shell: powershell

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Run SoapUI Tests
        run: |
          & ".\SoapUI\SoapUI-5.8.0\bin\testrunner.bat" -s "TestSuite4" -c "ValidarCorreoID" "Project2.xml"
        shell: powershell
